- hosts: localhost
  connection: local
  vars:
    str_1: john
    str_2: "{{ ffff  }}"
    value: "{{ '[\"' + str_1 + '\",\"' + str_2 + '\"]' | regex_escape()  }}"
  tasks:
    - name: "Print the_user"
      debug:
        msg: "{{ str_2 }}"