#!/bin/bash

# Fonction de complétion

_jtable_comp() {
    local cur prev opts
    cur="${COMP_WORDS[COMP_CWORD]}"    # Mot en cours de complétion
    prev="${COMP_WORDS[COMP_CWORD-1]}" # Mot précédent
    echo debug cur: ${cur}
    echo debug cur: ${prev}
    opts="start stop resume"
    jtable --help
    # echo debug COMP_WORDS: ${COMP_WORDS[@]}
    # echo debug COMP_CWORD: ${COMP_CWORD[@]}

    # Si c'est le premier argument, on propose les options
    if [[ ${COMP_CWORD} == 1 ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    fi
}

# install -m 644 jtable /usr/share/bash-completion/completions/

complete -F _jtable_comp jtable ./jtable
