- hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - views/hostvars.yml
  # vars:
  #   datafile: "{{ lookup('file', '../ansible/big_facts.json') | from_json  }}"
  
      


  tasks:
    - set_fact:
        host_view: "{{ (lookup('file', 'big_facts.json') | from_json).plays[0].tasks[0].hosts }}"


    # - debug: var=host_view_filtered.text
    # - debug: var=host_view_filtered.text
    # - debug: var=uptime.text
    # - debug: var=unreachable_hosts

    # - debug:
    #     msg: "{{ host_view | dict2items() | selectattr('value.unreachable','defined') | selectattr('value.unreachable','==',true)  }}"

    - set_fact:
        reports:
          - jack: "{{ host_view_filtered.json }}"
          - bob: "{{ uptime.json }}"
    
    - template:
        src: report_template.html.j2
        dest: host_view.html