default:
  tags:
    - docker
build_my_image:
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - "echo debug CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE"
    - docker ps

test:
  image: $CI_REGISTRY_IMAGE:latest
  script:
    - echo $HOSTNAME
    - pip install .
    - jtable -h
    - cd doc/examples
    - ./make_doc.sh --halt
    - ./diff_doc.sh ref_README.md README.md "line 365|line 366|line 225"

  artifacts:
    paths:
      - doc/examples/README.md
      - doc/examples/uptime_view_colored.html
    expire_in: 1 week
