name: Publish Python 🐍 package to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # déclenchement lors d’un tag, ex: v1.2.3

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build

      - name: Build the package
        run: |
          python -m build

      - name: Publish to PyPI using OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
