- hosts: localhost
  gather_facts: no
  vars:
    host_list:
      - { hostname: host_1, os: linux, cost: 5000, state: alive,service: {name: "service1\nservice_3"}  }
      - { hostname: host_2, os: linux1, cost: 200, state: alive }
      - { hostname: host_3, os: windows, cost: 200, state: alive }
      - { hostname: host_4, os: windows, cost: 5000, state: decom, ips: ['192.168.1.1','192.168.1.2'] }
      - { hostname: host_5, os: windows, cost: 5000, state: decom, ips: [] }
  tasks:
      
  - debug:
      msg: "{{ host_list | jtable }}"
    # vars:
      # path: "stdin{dc}{}"
      # select:
      # - as: dc
      #   expr: "dc.key"
      # - as: the hostname
      #   expr: "hostname"
      # - as: cost
      #   expr: "cost * 2"
      
        
      # - as: os
      #   expr: item.os | replace("linux", "youpi")

  # - debug:
  #     msg: "{{ (lookup('file', '../dataset.yml') | from_yaml).host | jtable(select) }}"
  #   vars:
  #     select: "{{ (lookup('file', 'jtable_query_sample.yml') | from_yaml).select }}"

        


