- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    min_host_per_group: 1
    max_host_per_group: 10
    dc:
      dc_1: West Coast
      dc_2: East Coast
      dc_3: Central
      dc_4: South
      dc_5: North
    depts:
      - it
      - hr
      - finance
      - sales
      - marketing
    envs:
      - dev
      - test
      - stage
      - prod
    hosts: "{{ range(min_host_per_group, max_host_per_group) | map('regex_replace', '^(.*)$', 'host\\1') | list }}"
    apps:
      - hyperion
      - essbase
      - planning
      - hfm
      - epm

    out_json: |
          {
          {% for dept in depts %}
          {% set properties = {'app': apps | random} %}
          "{{ dept }}": {
            "hosts": {"{{ hosts | join('":' + properties | string + ', "') }}": null }
          },
          {% endfor %}
          }

  tasks:

    - debug:
        msg: "{{ out_json  }}"
    - debug:
        msg: "{{ out_json  | type_debug }}"
    - copy:
        content: "{{ out_json  | to_nice_json }}"
        dest: ./generated_inv.json


    # - debug:
    #     msg: 
    #     - "{{ (depts | shuffle)[0:3]}}"
    #     - "{{ range(min_host_per_group, max_host_per_group) | random }}"
    