- hosts: all
  gather_facts: false
  tasks:
  - debug:
      msg: "{{ hostvars }}"
    delegate_to: localhost
    run_once: true
  
  # - set_stats:
  #     data:
  #       "{{ inventory_hostname.split('.')[0] }}": "{{ hostvars[inventory_hostname] }}"