context:
  hosts: "{{ stdin }}"
  dc:
    dc1: West Coast
    dc2: East Coast
    dc3: North Coast
  dataset: "{{ {'hosts': stdin, 'dc': dc} }}"

queryset:
  path: "[0].content.global_custom_stats"
  select:
  - as: localization
    expr: "dc[dc_view]"
  - as: dc
    expr: "dc_view"
  - as: name
    expr: key
  - as: value.app
    expr: value.app
  - as: value.group_names
    expr: value.group_names
  # - as: rmp port
  #   expr: value.rmp_port
  views:
    dc_view: "(value.group_names | intersect(dc))[0]"

out: '{{ dataset | jtable(select=select,path=path, format=format,vars=views ) }}'
# out: "{{ ds  | type_debug }}"
# out: '{{ ds | type_debug }}'