#!/bin/bash

# Fonction de complétion

_jtable_comp() {
    local cur prev opts
    cur="${COMP_WORDS[COMP_CWORD]}"    # Mot en cours de complétion
    prev="${COMP_WORDS[COMP_CWORD-1]}" # Mot précédent
    # echo debug cur: ${cur}
    # echo debug prev: ${prev}
    # echo debug COMP_WORDS: ${COMP_WORDS[@]}
    # echo debug opts: ${opts[@]}
    # opts="start stop resume"
    # jtable --help
    # echo debug COMP_WORDS: ${COMP_WORDS[@]}
    # echo debug COMP_CWORD: ${COMP_CWORD[@]}

    # Si c'est le premier argument, on propose les options
    input_files_options="-jf|-jfs|-yf|-yfs|--json_file|--json_files|--yaml_file|--yaml_files"
    case "${prev}" in
        --help)
            opts="start stop resume"
            ;;
        -jf|-jfs|-yf|-yfs|--json_file|--json_files|--yaml_file|--yaml_files)
            COMPREPLY=( $(compgen -f -- "$cur") )
            ;;
        -p|--path)
            # jtable --inspect | less 
            # for arg_index in ${COMP_CWORD}; do
            #     # echo debug ${COMP_WORDS[arg_index]}
            #     echo debug $arg_index
            # done

            for ((i = 0; i < ${COMP_CWORD}; i++)); do
                case ${COMP_WORDS[i]} in
                    -jf|-jfs|-yf|-yfs|--json_file|--json_files|--yaml_file|--yaml_files)
                        input_file=${COMP_WORDS[i+1]}
                        # echo debug input_file $input_file
                        cat $input_file | jtable --inspect | less
                        COMPREPLY=( $(compgen -f -- "$cur") )
                        ;;
                    *)
                        COMPREPLY=( $(compgen -d -- "$cur") )
                        ;;
                esac

            done
            COMPREPLY=( $(compgen -d -- "$cur") )
            ;;
    esac
    if [[ ${COMP_CWORD} == 1 ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    fi
}

# install -m 644 jtable /usr/share/bash-completion/completions/

complete -F _jtable_comp jtable ./jtable
